server:
  port: 8080

application:
  init:
    download-default-contacts: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/contacts
    username: postgres
    password: postgres
    hikari:
      schema: contacts_schema

logging:
  level:
    root: debug
